// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/mediaprocesstask"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
)

// MediaProcessTaskQuery is the builder for querying MediaProcessTask entities.
type MediaProcessTaskQuery struct {
	config
	ctx        *QueryContext
	order      []mediaprocesstask.OrderOption
	inters     []Interceptor
	predicates []predicate.MediaProcessTask
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MediaProcessTaskQuery builder.
func (mptq *MediaProcessTaskQuery) Where(ps ...predicate.MediaProcessTask) *MediaProcessTaskQuery {
	mptq.predicates = append(mptq.predicates, ps...)
	return mptq
}

// Limit the number of records to be returned by this query.
func (mptq *MediaProcessTaskQuery) Limit(limit int) *MediaProcessTaskQuery {
	mptq.ctx.Limit = &limit
	return mptq
}

// Offset to start from.
func (mptq *MediaProcessTaskQuery) Offset(offset int) *MediaProcessTaskQuery {
	mptq.ctx.Offset = &offset
	return mptq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mptq *MediaProcessTaskQuery) Unique(unique bool) *MediaProcessTaskQuery {
	mptq.ctx.Unique = &unique
	return mptq
}

// Order specifies how the records should be ordered.
func (mptq *MediaProcessTaskQuery) Order(o ...mediaprocesstask.OrderOption) *MediaProcessTaskQuery {
	mptq.order = append(mptq.order, o...)
	return mptq
}

// First returns the first MediaProcessTask entity from the query.
// Returns a *NotFoundError when no MediaProcessTask was found.
func (mptq *MediaProcessTaskQuery) First(ctx context.Context) (*MediaProcessTask, error) {
	nodes, err := mptq.Limit(1).All(setContextOp(ctx, mptq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{mediaprocesstask.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mptq *MediaProcessTaskQuery) FirstX(ctx context.Context) *MediaProcessTask {
	node, err := mptq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MediaProcessTask ID from the query.
// Returns a *NotFoundError when no MediaProcessTask ID was found.
func (mptq *MediaProcessTaskQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mptq.Limit(1).IDs(setContextOp(ctx, mptq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{mediaprocesstask.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mptq *MediaProcessTaskQuery) FirstIDX(ctx context.Context) int {
	id, err := mptq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MediaProcessTask entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MediaProcessTask entity is found.
// Returns a *NotFoundError when no MediaProcessTask entities are found.
func (mptq *MediaProcessTaskQuery) Only(ctx context.Context) (*MediaProcessTask, error) {
	nodes, err := mptq.Limit(2).All(setContextOp(ctx, mptq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{mediaprocesstask.Label}
	default:
		return nil, &NotSingularError{mediaprocesstask.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mptq *MediaProcessTaskQuery) OnlyX(ctx context.Context) *MediaProcessTask {
	node, err := mptq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MediaProcessTask ID in the query.
// Returns a *NotSingularError when more than one MediaProcessTask ID is found.
// Returns a *NotFoundError when no entities are found.
func (mptq *MediaProcessTaskQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mptq.Limit(2).IDs(setContextOp(ctx, mptq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{mediaprocesstask.Label}
	default:
		err = &NotSingularError{mediaprocesstask.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mptq *MediaProcessTaskQuery) OnlyIDX(ctx context.Context) int {
	id, err := mptq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MediaProcessTasks.
func (mptq *MediaProcessTaskQuery) All(ctx context.Context) ([]*MediaProcessTask, error) {
	ctx = setContextOp(ctx, mptq.ctx, "All")
	if err := mptq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MediaProcessTask, *MediaProcessTaskQuery]()
	return withInterceptors[[]*MediaProcessTask](ctx, mptq, qr, mptq.inters)
}

// AllX is like All, but panics if an error occurs.
func (mptq *MediaProcessTaskQuery) AllX(ctx context.Context) []*MediaProcessTask {
	nodes, err := mptq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MediaProcessTask IDs.
func (mptq *MediaProcessTaskQuery) IDs(ctx context.Context) (ids []int, err error) {
	if mptq.ctx.Unique == nil && mptq.path != nil {
		mptq.Unique(true)
	}
	ctx = setContextOp(ctx, mptq.ctx, "IDs")
	if err = mptq.Select(mediaprocesstask.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mptq *MediaProcessTaskQuery) IDsX(ctx context.Context) []int {
	ids, err := mptq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mptq *MediaProcessTaskQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, mptq.ctx, "Count")
	if err := mptq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, mptq, querierCount[*MediaProcessTaskQuery](), mptq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (mptq *MediaProcessTaskQuery) CountX(ctx context.Context) int {
	count, err := mptq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mptq *MediaProcessTaskQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, mptq.ctx, "Exist")
	switch _, err := mptq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (mptq *MediaProcessTaskQuery) ExistX(ctx context.Context) bool {
	exist, err := mptq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MediaProcessTaskQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mptq *MediaProcessTaskQuery) Clone() *MediaProcessTaskQuery {
	if mptq == nil {
		return nil
	}
	return &MediaProcessTaskQuery{
		config:     mptq.config,
		ctx:        mptq.ctx.Clone(),
		order:      append([]mediaprocesstask.OrderOption{}, mptq.order...),
		inters:     append([]Interceptor{}, mptq.inters...),
		predicates: append([]predicate.MediaProcessTask{}, mptq.predicates...),
		// clone intermediate query.
		sql:  mptq.sql.Clone(),
		path: mptq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MediaProcessTask.Query().
//		GroupBy(mediaprocesstask.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (mptq *MediaProcessTaskQuery) GroupBy(field string, fields ...string) *MediaProcessTaskGroupBy {
	mptq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MediaProcessTaskGroupBy{build: mptq}
	grbuild.flds = &mptq.ctx.Fields
	grbuild.label = mediaprocesstask.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.MediaProcessTask.Query().
//		Select(mediaprocesstask.FieldCreatedAt).
//		Scan(ctx, &v)
func (mptq *MediaProcessTaskQuery) Select(fields ...string) *MediaProcessTaskSelect {
	mptq.ctx.Fields = append(mptq.ctx.Fields, fields...)
	sbuild := &MediaProcessTaskSelect{MediaProcessTaskQuery: mptq}
	sbuild.label = mediaprocesstask.Label
	sbuild.flds, sbuild.scan = &mptq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MediaProcessTaskSelect configured with the given aggregations.
func (mptq *MediaProcessTaskQuery) Aggregate(fns ...AggregateFunc) *MediaProcessTaskSelect {
	return mptq.Select().Aggregate(fns...)
}

func (mptq *MediaProcessTaskQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range mptq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, mptq); err != nil {
				return err
			}
		}
	}
	for _, f := range mptq.ctx.Fields {
		if !mediaprocesstask.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mptq.path != nil {
		prev, err := mptq.path(ctx)
		if err != nil {
			return err
		}
		mptq.sql = prev
	}
	return nil
}

func (mptq *MediaProcessTaskQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MediaProcessTask, error) {
	var (
		nodes = []*MediaProcessTask{}
		_spec = mptq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MediaProcessTask).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MediaProcessTask{config: mptq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mptq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (mptq *MediaProcessTaskQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mptq.querySpec()
	_spec.Node.Columns = mptq.ctx.Fields
	if len(mptq.ctx.Fields) > 0 {
		_spec.Unique = mptq.ctx.Unique != nil && *mptq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, mptq.driver, _spec)
}

func (mptq *MediaProcessTaskQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(mediaprocesstask.Table, mediaprocesstask.Columns, sqlgraph.NewFieldSpec(mediaprocesstask.FieldID, field.TypeInt))
	_spec.From = mptq.sql
	if unique := mptq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if mptq.path != nil {
		_spec.Unique = true
	}
	if fields := mptq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mediaprocesstask.FieldID)
		for i := range fields {
			if fields[i] != mediaprocesstask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := mptq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mptq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mptq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mptq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mptq *MediaProcessTaskQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mptq.driver.Dialect())
	t1 := builder.Table(mediaprocesstask.Table)
	columns := mptq.ctx.Fields
	if len(columns) == 0 {
		columns = mediaprocesstask.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mptq.sql != nil {
		selector = mptq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mptq.ctx.Unique != nil && *mptq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range mptq.predicates {
		p(selector)
	}
	for _, p := range mptq.order {
		p(selector)
	}
	if offset := mptq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mptq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MediaProcessTaskGroupBy is the group-by builder for MediaProcessTask entities.
type MediaProcessTaskGroupBy struct {
	selector
	build *MediaProcessTaskQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mptgb *MediaProcessTaskGroupBy) Aggregate(fns ...AggregateFunc) *MediaProcessTaskGroupBy {
	mptgb.fns = append(mptgb.fns, fns...)
	return mptgb
}

// Scan applies the selector query and scans the result into the given value.
func (mptgb *MediaProcessTaskGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mptgb.build.ctx, "GroupBy")
	if err := mptgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MediaProcessTaskQuery, *MediaProcessTaskGroupBy](ctx, mptgb.build, mptgb, mptgb.build.inters, v)
}

func (mptgb *MediaProcessTaskGroupBy) sqlScan(ctx context.Context, root *MediaProcessTaskQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(mptgb.fns))
	for _, fn := range mptgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*mptgb.flds)+len(mptgb.fns))
		for _, f := range *mptgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*mptgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mptgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MediaProcessTaskSelect is the builder for selecting fields of MediaProcessTask entities.
type MediaProcessTaskSelect struct {
	*MediaProcessTaskQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mpts *MediaProcessTaskSelect) Aggregate(fns ...AggregateFunc) *MediaProcessTaskSelect {
	mpts.fns = append(mpts.fns, fns...)
	return mpts
}

// Scan applies the selector query and scans the result into the given value.
func (mpts *MediaProcessTaskSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mpts.ctx, "Select")
	if err := mpts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MediaProcessTaskQuery, *MediaProcessTaskSelect](ctx, mpts.MediaProcessTaskQuery, mpts, mpts.inters, v)
}

func (mpts *MediaProcessTaskSelect) sqlScan(ctx context.Context, root *MediaProcessTaskQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(mpts.fns))
	for _, fn := range mpts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*mpts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mpts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
