// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/cloudreve/Cloudreve/v4/ent/mediaprocesstask"
	"github.com/cloudreve/Cloudreve/v4/inventory/types"
)

// MediaProcessTask is the model entity for the MediaProcessTask schema.
type MediaProcessTask struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// MediaType holds the value of the "media_type" field.
	MediaType mediaprocesstask.MediaType `json:"media_type,omitempty"`
	// Status holds the value of the "status" field.
	Status mediaprocesstask.Status `json:"status,omitempty"`
	// EntityID holds the value of the "entity_id" field.
	EntityID int `json:"entity_id,omitempty"`
	// FileID holds the value of the "file_id" field.
	FileID int `json:"file_id,omitempty"`
	// OwnerID holds the value of the "owner_id" field.
	OwnerID int `json:"owner_id,omitempty"`
	// Attempts holds the value of the "attempts" field.
	Attempts int `json:"attempts,omitempty"`
	// Error holds the value of the "error" field.
	Error string `json:"error,omitempty"`
	// ResultSize holds the value of the "result_size" field.
	ResultSize int64 `json:"result_size,omitempty"`
	// Props holds the value of the "props" field.
	Props        *types.MediaProcessTaskProps `json:"props,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MediaProcessTask) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case mediaprocesstask.FieldProps:
			values[i] = new([]byte)
		case mediaprocesstask.FieldID, mediaprocesstask.FieldEntityID, mediaprocesstask.FieldFileID, mediaprocesstask.FieldOwnerID, mediaprocesstask.FieldAttempts, mediaprocesstask.FieldResultSize:
			values[i] = new(sql.NullInt64)
		case mediaprocesstask.FieldMediaType, mediaprocesstask.FieldStatus, mediaprocesstask.FieldError:
			values[i] = new(sql.NullString)
		case mediaprocesstask.FieldCreatedAt, mediaprocesstask.FieldUpdatedAt, mediaprocesstask.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MediaProcessTask fields.
func (mpt *MediaProcessTask) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case mediaprocesstask.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			mpt.ID = int(value.Int64)
		case mediaprocesstask.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				mpt.CreatedAt = value.Time
			}
		case mediaprocesstask.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				mpt.UpdatedAt = value.Time
			}
		case mediaprocesstask.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				mpt.DeletedAt = new(time.Time)
				*mpt.DeletedAt = value.Time
			}
		case mediaprocesstask.FieldMediaType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field media_type", values[i])
			} else if value.Valid {
				mpt.MediaType = mediaprocesstask.MediaType(value.String)
			}
		case mediaprocesstask.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				mpt.Status = mediaprocesstask.Status(value.String)
			}
		case mediaprocesstask.FieldEntityID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field entity_id", values[i])
			} else if value.Valid {
				mpt.EntityID = int(value.Int64)
			}
		case mediaprocesstask.FieldFileID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field file_id", values[i])
			} else if value.Valid {
				mpt.FileID = int(value.Int64)
			}
		case mediaprocesstask.FieldOwnerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field owner_id", values[i])
			} else if value.Valid {
				mpt.OwnerID = int(value.Int64)
			}
		case mediaprocesstask.FieldAttempts:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempts", values[i])
			} else if value.Valid {
				mpt.Attempts = int(value.Int64)
			}
		case mediaprocesstask.FieldError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error", values[i])
			} else if value.Valid {
				mpt.Error = value.String
			}
		case mediaprocesstask.FieldResultSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field result_size", values[i])
			} else if value.Valid {
				mpt.ResultSize = value.Int64
			}
		case mediaprocesstask.FieldProps:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field props", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &mpt.Props); err != nil {
					return fmt.Errorf("unmarshal field props: %w", err)
				}
			}
		default:
			mpt.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MediaProcessTask.
// This includes values selected through modifiers, order, etc.
func (mpt *MediaProcessTask) Value(name string) (ent.Value, error) {
	return mpt.selectValues.Get(name)
}

// Update returns a builder for updating this MediaProcessTask.
// Note that you need to call MediaProcessTask.Unwrap() before calling this method if this MediaProcessTask
// was returned from a transaction, and the transaction was committed or rolled back.
func (mpt *MediaProcessTask) Update() *MediaProcessTaskUpdateOne {
	return NewMediaProcessTaskClient(mpt.config).UpdateOne(mpt)
}

// Unwrap unwraps the MediaProcessTask entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (mpt *MediaProcessTask) Unwrap() *MediaProcessTask {
	_tx, ok := mpt.config.driver.(*txDriver)
	if !ok {
		panic("ent: MediaProcessTask is not a transactional entity")
	}
	mpt.config.driver = _tx.drv
	return mpt
}

// String implements the fmt.Stringer.
func (mpt *MediaProcessTask) String() string {
	var builder strings.Builder
	builder.WriteString("MediaProcessTask(")
	builder.WriteString(fmt.Sprintf("id=%v, ", mpt.ID))
	builder.WriteString("created_at=")
	builder.WriteString(mpt.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(mpt.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := mpt.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("media_type=")
	builder.WriteString(fmt.Sprintf("%v", mpt.MediaType))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", mpt.Status))
	builder.WriteString(", ")
	builder.WriteString("entity_id=")
	builder.WriteString(fmt.Sprintf("%v", mpt.EntityID))
	builder.WriteString(", ")
	builder.WriteString("file_id=")
	builder.WriteString(fmt.Sprintf("%v", mpt.FileID))
	builder.WriteString(", ")
	builder.WriteString("owner_id=")
	builder.WriteString(fmt.Sprintf("%v", mpt.OwnerID))
	builder.WriteString(", ")
	builder.WriteString("attempts=")
	builder.WriteString(fmt.Sprintf("%v", mpt.Attempts))
	builder.WriteString(", ")
	builder.WriteString("error=")
	builder.WriteString(mpt.Error)
	builder.WriteString(", ")
	builder.WriteString("result_size=")
	builder.WriteString(fmt.Sprintf("%v", mpt.ResultSize))
	builder.WriteString(", ")
	builder.WriteString("props=")
	builder.WriteString(fmt.Sprintf("%v", mpt.Props))
	builder.WriteByte(')')
	return builder.String()
}

// MediaProcessTasks is a parsable slice of MediaProcessTask.
type MediaProcessTasks []*MediaProcessTask
