// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/mediaprocesstask"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
	"github.com/cloudreve/Cloudreve/v4/inventory/types"
)

// MediaProcessTaskUpdate is the builder for updating MediaProcessTask entities.
type MediaProcessTaskUpdate struct {
	config
	hooks    []Hook
	mutation *MediaProcessTaskMutation
}

// Where appends a list predicates to the MediaProcessTaskUpdate builder.
func (mptu *MediaProcessTaskUpdate) Where(ps ...predicate.MediaProcessTask) *MediaProcessTaskUpdate {
	mptu.mutation.Where(ps...)
	return mptu
}

// SetUpdatedAt sets the "updated_at" field.
func (mptu *MediaProcessTaskUpdate) SetUpdatedAt(t time.Time) *MediaProcessTaskUpdate {
	mptu.mutation.SetUpdatedAt(t)
	return mptu
}

// SetDeletedAt sets the "deleted_at" field.
func (mptu *MediaProcessTaskUpdate) SetDeletedAt(t time.Time) *MediaProcessTaskUpdate {
	mptu.mutation.SetDeletedAt(t)
	return mptu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (mptu *MediaProcessTaskUpdate) SetNillableDeletedAt(t *time.Time) *MediaProcessTaskUpdate {
	if t != nil {
		mptu.SetDeletedAt(*t)
	}
	return mptu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (mptu *MediaProcessTaskUpdate) ClearDeletedAt() *MediaProcessTaskUpdate {
	mptu.mutation.ClearDeletedAt()
	return mptu
}

// SetMediaType sets the "media_type" field.
func (mptu *MediaProcessTaskUpdate) SetMediaType(mt mediaprocesstask.MediaType) *MediaProcessTaskUpdate {
	mptu.mutation.SetMediaType(mt)
	return mptu
}

// SetNillableMediaType sets the "media_type" field if the given value is not nil.
func (mptu *MediaProcessTaskUpdate) SetNillableMediaType(mt *mediaprocesstask.MediaType) *MediaProcessTaskUpdate {
	if mt != nil {
		mptu.SetMediaType(*mt)
	}
	return mptu
}

// SetStatus sets the "status" field.
func (mptu *MediaProcessTaskUpdate) SetStatus(m mediaprocesstask.Status) *MediaProcessTaskUpdate {
	mptu.mutation.SetStatus(m)
	return mptu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (mptu *MediaProcessTaskUpdate) SetNillableStatus(m *mediaprocesstask.Status) *MediaProcessTaskUpdate {
	if m != nil {
		mptu.SetStatus(*m)
	}
	return mptu
}

// SetEntityID sets the "entity_id" field.
func (mptu *MediaProcessTaskUpdate) SetEntityID(i int) *MediaProcessTaskUpdate {
	mptu.mutation.ResetEntityID()
	mptu.mutation.SetEntityID(i)
	return mptu
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (mptu *MediaProcessTaskUpdate) SetNillableEntityID(i *int) *MediaProcessTaskUpdate {
	if i != nil {
		mptu.SetEntityID(*i)
	}
	return mptu
}

// AddEntityID adds i to the "entity_id" field.
func (mptu *MediaProcessTaskUpdate) AddEntityID(i int) *MediaProcessTaskUpdate {
	mptu.mutation.AddEntityID(i)
	return mptu
}

// SetFileID sets the "file_id" field.
func (mptu *MediaProcessTaskUpdate) SetFileID(i int) *MediaProcessTaskUpdate {
	mptu.mutation.ResetFileID()
	mptu.mutation.SetFileID(i)
	return mptu
}

// SetNillableFileID sets the "file_id" field if the given value is not nil.
func (mptu *MediaProcessTaskUpdate) SetNillableFileID(i *int) *MediaProcessTaskUpdate {
	if i != nil {
		mptu.SetFileID(*i)
	}
	return mptu
}

// AddFileID adds i to the "file_id" field.
func (mptu *MediaProcessTaskUpdate) AddFileID(i int) *MediaProcessTaskUpdate {
	mptu.mutation.AddFileID(i)
	return mptu
}

// ClearFileID clears the value of the "file_id" field.
func (mptu *MediaProcessTaskUpdate) ClearFileID() *MediaProcessTaskUpdate {
	mptu.mutation.ClearFileID()
	return mptu
}

// SetOwnerID sets the "owner_id" field.
func (mptu *MediaProcessTaskUpdate) SetOwnerID(i int) *MediaProcessTaskUpdate {
	mptu.mutation.ResetOwnerID()
	mptu.mutation.SetOwnerID(i)
	return mptu
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (mptu *MediaProcessTaskUpdate) SetNillableOwnerID(i *int) *MediaProcessTaskUpdate {
	if i != nil {
		mptu.SetOwnerID(*i)
	}
	return mptu
}

// AddOwnerID adds i to the "owner_id" field.
func (mptu *MediaProcessTaskUpdate) AddOwnerID(i int) *MediaProcessTaskUpdate {
	mptu.mutation.AddOwnerID(i)
	return mptu
}

// SetAttempts sets the "attempts" field.
func (mptu *MediaProcessTaskUpdate) SetAttempts(i int) *MediaProcessTaskUpdate {
	mptu.mutation.ResetAttempts()
	mptu.mutation.SetAttempts(i)
	return mptu
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (mptu *MediaProcessTaskUpdate) SetNillableAttempts(i *int) *MediaProcessTaskUpdate {
	if i != nil {
		mptu.SetAttempts(*i)
	}
	return mptu
}

// AddAttempts adds i to the "attempts" field.
func (mptu *MediaProcessTaskUpdate) AddAttempts(i int) *MediaProcessTaskUpdate {
	mptu.mutation.AddAttempts(i)
	return mptu
}

// SetError sets the "error" field.
func (mptu *MediaProcessTaskUpdate) SetError(s string) *MediaProcessTaskUpdate {
	mptu.mutation.SetError(s)
	return mptu
}

// SetNillableError sets the "error" field if the given value is not nil.
func (mptu *MediaProcessTaskUpdate) SetNillableError(s *string) *MediaProcessTaskUpdate {
	if s != nil {
		mptu.SetError(*s)
	}
	return mptu
}

// ClearError clears the value of the "error" field.
func (mptu *MediaProcessTaskUpdate) ClearError() *MediaProcessTaskUpdate {
	mptu.mutation.ClearError()
	return mptu
}

// SetResultSize sets the "result_size" field.
func (mptu *MediaProcessTaskUpdate) SetResultSize(i int64) *MediaProcessTaskUpdate {
	mptu.mutation.ResetResultSize()
	mptu.mutation.SetResultSize(i)
	return mptu
}

// SetNillableResultSize sets the "result_size" field if the given value is not nil.
func (mptu *MediaProcessTaskUpdate) SetNillableResultSize(i *int64) *MediaProcessTaskUpdate {
	if i != nil {
		mptu.SetResultSize(*i)
	}
	return mptu
}

// AddResultSize adds i to the "result_size" field.
func (mptu *MediaProcessTaskUpdate) AddResultSize(i int64) *MediaProcessTaskUpdate {
	mptu.mutation.AddResultSize(i)
	return mptu
}

// ClearResultSize clears the value of the "result_size" field.
func (mptu *MediaProcessTaskUpdate) ClearResultSize() *MediaProcessTaskUpdate {
	mptu.mutation.ClearResultSize()
	return mptu
}

// SetProps sets the "props" field.
func (mptu *MediaProcessTaskUpdate) SetProps(tptp *types.MediaProcessTaskProps) *MediaProcessTaskUpdate {
	mptu.mutation.SetProps(tptp)
	return mptu
}

// ClearProps clears the value of the "props" field.
func (mptu *MediaProcessTaskUpdate) ClearProps() *MediaProcessTaskUpdate {
	mptu.mutation.ClearProps()
	return mptu
}

// Mutation returns the MediaProcessTaskMutation object of the builder.
func (mptu *MediaProcessTaskUpdate) Mutation() *MediaProcessTaskMutation {
	return mptu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mptu *MediaProcessTaskUpdate) Save(ctx context.Context) (int, error) {
	if err := mptu.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, mptu.sqlSave, mptu.mutation, mptu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mptu *MediaProcessTaskUpdate) SaveX(ctx context.Context) int {
	affected, err := mptu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mptu *MediaProcessTaskUpdate) Exec(ctx context.Context) error {
	_, err := mptu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mptu *MediaProcessTaskUpdate) ExecX(ctx context.Context) {
	if err := mptu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mptu *MediaProcessTaskUpdate) defaults() error {
	if _, ok := mptu.mutation.UpdatedAt(); !ok {
		if mediaprocesstask.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized mediaprocesstask.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := mediaprocesstask.UpdateDefaultUpdatedAt()
		mptu.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (mptu *MediaProcessTaskUpdate) check() error {
	if v, ok := mptu.mutation.MediaType(); ok {
		if err := mediaprocesstask.MediaTypeValidator(v); err != nil {
			return &ValidationError{Name: "media_type", err: fmt.Errorf(`ent: validator failed for field "MediaProcessTask.media_type": %w`, err)}
		}
	}
	if v, ok := mptu.mutation.Status(); ok {
		if err := mediaprocesstask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MediaProcessTask.status": %w`, err)}
		}
	}
	return nil
}

func (mptu *MediaProcessTaskUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := mptu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(mediaprocesstask.Table, mediaprocesstask.Columns, sqlgraph.NewFieldSpec(mediaprocesstask.FieldID, field.TypeInt))
	if ps := mptu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mptu.mutation.UpdatedAt(); ok {
		_spec.SetField(mediaprocesstask.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := mptu.mutation.DeletedAt(); ok {
		_spec.SetField(mediaprocesstask.FieldDeletedAt, field.TypeTime, value)
	}
	if mptu.mutation.DeletedAtCleared() {
		_spec.ClearField(mediaprocesstask.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := mptu.mutation.MediaType(); ok {
		_spec.SetField(mediaprocesstask.FieldMediaType, field.TypeEnum, value)
	}
	if value, ok := mptu.mutation.Status(); ok {
		_spec.SetField(mediaprocesstask.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := mptu.mutation.EntityID(); ok {
		_spec.SetField(mediaprocesstask.FieldEntityID, field.TypeInt, value)
	}
	if value, ok := mptu.mutation.AddedEntityID(); ok {
		_spec.AddField(mediaprocesstask.FieldEntityID, field.TypeInt, value)
	}
	if value, ok := mptu.mutation.FileID(); ok {
		_spec.SetField(mediaprocesstask.FieldFileID, field.TypeInt, value)
	}
	if value, ok := mptu.mutation.AddedFileID(); ok {
		_spec.AddField(mediaprocesstask.FieldFileID, field.TypeInt, value)
	}
	if mptu.mutation.FileIDCleared() {
		_spec.ClearField(mediaprocesstask.FieldFileID, field.TypeInt)
	}
	if value, ok := mptu.mutation.OwnerID(); ok {
		_spec.SetField(mediaprocesstask.FieldOwnerID, field.TypeInt, value)
	}
	if value, ok := mptu.mutation.AddedOwnerID(); ok {
		_spec.AddField(mediaprocesstask.FieldOwnerID, field.TypeInt, value)
	}
	if value, ok := mptu.mutation.Attempts(); ok {
		_spec.SetField(mediaprocesstask.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := mptu.mutation.AddedAttempts(); ok {
		_spec.AddField(mediaprocesstask.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := mptu.mutation.Error(); ok {
		_spec.SetField(mediaprocesstask.FieldError, field.TypeString, value)
	}
	if mptu.mutation.ErrorCleared() {
		_spec.ClearField(mediaprocesstask.FieldError, field.TypeString)
	}
	if value, ok := mptu.mutation.ResultSize(); ok {
		_spec.SetField(mediaprocesstask.FieldResultSize, field.TypeInt64, value)
	}
	if value, ok := mptu.mutation.AddedResultSize(); ok {
		_spec.AddField(mediaprocesstask.FieldResultSize, field.TypeInt64, value)
	}
	if mptu.mutation.ResultSizeCleared() {
		_spec.ClearField(mediaprocesstask.FieldResultSize, field.TypeInt64)
	}
	if value, ok := mptu.mutation.Props(); ok {
		_spec.SetField(mediaprocesstask.FieldProps, field.TypeJSON, value)
	}
	if mptu.mutation.PropsCleared() {
		_spec.ClearField(mediaprocesstask.FieldProps, field.TypeJSON)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mptu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mediaprocesstask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mptu.mutation.done = true
	return n, nil
}

// MediaProcessTaskUpdateOne is the builder for updating a single MediaProcessTask entity.
type MediaProcessTaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MediaProcessTaskMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (mptuo *MediaProcessTaskUpdateOne) SetUpdatedAt(t time.Time) *MediaProcessTaskUpdateOne {
	mptuo.mutation.SetUpdatedAt(t)
	return mptuo
}

// SetDeletedAt sets the "deleted_at" field.
func (mptuo *MediaProcessTaskUpdateOne) SetDeletedAt(t time.Time) *MediaProcessTaskUpdateOne {
	mptuo.mutation.SetDeletedAt(t)
	return mptuo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (mptuo *MediaProcessTaskUpdateOne) SetNillableDeletedAt(t *time.Time) *MediaProcessTaskUpdateOne {
	if t != nil {
		mptuo.SetDeletedAt(*t)
	}
	return mptuo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (mptuo *MediaProcessTaskUpdateOne) ClearDeletedAt() *MediaProcessTaskUpdateOne {
	mptuo.mutation.ClearDeletedAt()
	return mptuo
}

// SetMediaType sets the "media_type" field.
func (mptuo *MediaProcessTaskUpdateOne) SetMediaType(mt mediaprocesstask.MediaType) *MediaProcessTaskUpdateOne {
	mptuo.mutation.SetMediaType(mt)
	return mptuo
}

// SetNillableMediaType sets the "media_type" field if the given value is not nil.
func (mptuo *MediaProcessTaskUpdateOne) SetNillableMediaType(mt *mediaprocesstask.MediaType) *MediaProcessTaskUpdateOne {
	if mt != nil {
		mptuo.SetMediaType(*mt)
	}
	return mptuo
}

// SetStatus sets the "status" field.
func (mptuo *MediaProcessTaskUpdateOne) SetStatus(m mediaprocesstask.Status) *MediaProcessTaskUpdateOne {
	mptuo.mutation.SetStatus(m)
	return mptuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (mptuo *MediaProcessTaskUpdateOne) SetNillableStatus(m *mediaprocesstask.Status) *MediaProcessTaskUpdateOne {
	if m != nil {
		mptuo.SetStatus(*m)
	}
	return mptuo
}

// SetEntityID sets the "entity_id" field.
func (mptuo *MediaProcessTaskUpdateOne) SetEntityID(i int) *MediaProcessTaskUpdateOne {
	mptuo.mutation.ResetEntityID()
	mptuo.mutation.SetEntityID(i)
	return mptuo
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (mptuo *MediaProcessTaskUpdateOne) SetNillableEntityID(i *int) *MediaProcessTaskUpdateOne {
	if i != nil {
		mptuo.SetEntityID(*i)
	}
	return mptuo
}

// AddEntityID adds i to the "entity_id" field.
func (mptuo *MediaProcessTaskUpdateOne) AddEntityID(i int) *MediaProcessTaskUpdateOne {
	mptuo.mutation.AddEntityID(i)
	return mptuo
}

// SetFileID sets the "file_id" field.
func (mptuo *MediaProcessTaskUpdateOne) SetFileID(i int) *MediaProcessTaskUpdateOne {
	mptuo.mutation.ResetFileID()
	mptuo.mutation.SetFileID(i)
	return mptuo
}

// SetNillableFileID sets the "file_id" field if the given value is not nil.
func (mptuo *MediaProcessTaskUpdateOne) SetNillableFileID(i *int) *MediaProcessTaskUpdateOne {
	if i != nil {
		mptuo.SetFileID(*i)
	}
	return mptuo
}

// AddFileID adds i to the "file_id" field.
func (mptuo *MediaProcessTaskUpdateOne) AddFileID(i int) *MediaProcessTaskUpdateOne {
	mptuo.mutation.AddFileID(i)
	return mptuo
}

// ClearFileID clears the value of the "file_id" field.
func (mptuo *MediaProcessTaskUpdateOne) ClearFileID() *MediaProcessTaskUpdateOne {
	mptuo.mutation.ClearFileID()
	return mptuo
}

// SetOwnerID sets the "owner_id" field.
func (mptuo *MediaProcessTaskUpdateOne) SetOwnerID(i int) *MediaProcessTaskUpdateOne {
	mptuo.mutation.ResetOwnerID()
	mptuo.mutation.SetOwnerID(i)
	return mptuo
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (mptuo *MediaProcessTaskUpdateOne) SetNillableOwnerID(i *int) *MediaProcessTaskUpdateOne {
	if i != nil {
		mptuo.SetOwnerID(*i)
	}
	return mptuo
}

// AddOwnerID adds i to the "owner_id" field.
func (mptuo *MediaProcessTaskUpdateOne) AddOwnerID(i int) *MediaProcessTaskUpdateOne {
	mptuo.mutation.AddOwnerID(i)
	return mptuo
}

// SetAttempts sets the "attempts" field.
func (mptuo *MediaProcessTaskUpdateOne) SetAttempts(i int) *MediaProcessTaskUpdateOne {
	mptuo.mutation.ResetAttempts()
	mptuo.mutation.SetAttempts(i)
	return mptuo
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (mptuo *MediaProcessTaskUpdateOne) SetNillableAttempts(i *int) *MediaProcessTaskUpdateOne {
	if i != nil {
		mptuo.SetAttempts(*i)
	}
	return mptuo
}

// AddAttempts adds i to the "attempts" field.
func (mptuo *MediaProcessTaskUpdateOne) AddAttempts(i int) *MediaProcessTaskUpdateOne {
	mptuo.mutation.AddAttempts(i)
	return mptuo
}

// SetError sets the "error" field.
func (mptuo *MediaProcessTaskUpdateOne) SetError(s string) *MediaProcessTaskUpdateOne {
	mptuo.mutation.SetError(s)
	return mptuo
}

// SetNillableError sets the "error" field if the given value is not nil.
func (mptuo *MediaProcessTaskUpdateOne) SetNillableError(s *string) *MediaProcessTaskUpdateOne {
	if s != nil {
		mptuo.SetError(*s)
	}
	return mptuo
}

// ClearError clears the value of the "error" field.
func (mptuo *MediaProcessTaskUpdateOne) ClearError() *MediaProcessTaskUpdateOne {
	mptuo.mutation.ClearError()
	return mptuo
}

// SetResultSize sets the "result_size" field.
func (mptuo *MediaProcessTaskUpdateOne) SetResultSize(i int64) *MediaProcessTaskUpdateOne {
	mptuo.mutation.ResetResultSize()
	mptuo.mutation.SetResultSize(i)
	return mptuo
}

// SetNillableResultSize sets the "result_size" field if the given value is not nil.
func (mptuo *MediaProcessTaskUpdateOne) SetNillableResultSize(i *int64) *MediaProcessTaskUpdateOne {
	if i != nil {
		mptuo.SetResultSize(*i)
	}
	return mptuo
}

// AddResultSize adds i to the "result_size" field.
func (mptuo *MediaProcessTaskUpdateOne) AddResultSize(i int64) *MediaProcessTaskUpdateOne {
	mptuo.mutation.AddResultSize(i)
	return mptuo
}

// ClearResultSize clears the value of the "result_size" field.
func (mptuo *MediaProcessTaskUpdateOne) ClearResultSize() *MediaProcessTaskUpdateOne {
	mptuo.mutation.ClearResultSize()
	return mptuo
}

// SetProps sets the "props" field.
func (mptuo *MediaProcessTaskUpdateOne) SetProps(tptp *types.MediaProcessTaskProps) *MediaProcessTaskUpdateOne {
	mptuo.mutation.SetProps(tptp)
	return mptuo
}

// ClearProps clears the value of the "props" field.
func (mptuo *MediaProcessTaskUpdateOne) ClearProps() *MediaProcessTaskUpdateOne {
	mptuo.mutation.ClearProps()
	return mptuo
}

// Mutation returns the MediaProcessTaskMutation object of the builder.
func (mptuo *MediaProcessTaskUpdateOne) Mutation() *MediaProcessTaskMutation {
	return mptuo.mutation
}

// Where appends a list predicates to the MediaProcessTaskUpdate builder.
func (mptuo *MediaProcessTaskUpdateOne) Where(ps ...predicate.MediaProcessTask) *MediaProcessTaskUpdateOne {
	mptuo.mutation.Where(ps...)
	return mptuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (mptuo *MediaProcessTaskUpdateOne) Select(field string, fields ...string) *MediaProcessTaskUpdateOne {
	mptuo.fields = append([]string{field}, fields...)
	return mptuo
}

// Save executes the query and returns the updated MediaProcessTask entity.
func (mptuo *MediaProcessTaskUpdateOne) Save(ctx context.Context) (*MediaProcessTask, error) {
	if err := mptuo.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, mptuo.sqlSave, mptuo.mutation, mptuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mptuo *MediaProcessTaskUpdateOne) SaveX(ctx context.Context) *MediaProcessTask {
	node, err := mptuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (mptuo *MediaProcessTaskUpdateOne) Exec(ctx context.Context) error {
	_, err := mptuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mptuo *MediaProcessTaskUpdateOne) ExecX(ctx context.Context) {
	if err := mptuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mptuo *MediaProcessTaskUpdateOne) defaults() error {
	if _, ok := mptuo.mutation.UpdatedAt(); !ok {
		if mediaprocesstask.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized mediaprocesstask.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := mediaprocesstask.UpdateDefaultUpdatedAt()
		mptuo.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (mptuo *MediaProcessTaskUpdateOne) check() error {
	if v, ok := mptuo.mutation.MediaType(); ok {
		if err := mediaprocesstask.MediaTypeValidator(v); err != nil {
			return &ValidationError{Name: "media_type", err: fmt.Errorf(`ent: validator failed for field "MediaProcessTask.media_type": %w`, err)}
		}
	}
	if v, ok := mptuo.mutation.Status(); ok {
		if err := mediaprocesstask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MediaProcessTask.status": %w`, err)}
		}
	}
	return nil
}

func (mptuo *MediaProcessTaskUpdateOne) sqlSave(ctx context.Context) (_node *MediaProcessTask, err error) {
	if err := mptuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mediaprocesstask.Table, mediaprocesstask.Columns, sqlgraph.NewFieldSpec(mediaprocesstask.FieldID, field.TypeInt))
	id, ok := mptuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MediaProcessTask.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := mptuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mediaprocesstask.FieldID)
		for _, f := range fields {
			if !mediaprocesstask.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mediaprocesstask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := mptuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mptuo.mutation.UpdatedAt(); ok {
		_spec.SetField(mediaprocesstask.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := mptuo.mutation.DeletedAt(); ok {
		_spec.SetField(mediaprocesstask.FieldDeletedAt, field.TypeTime, value)
	}
	if mptuo.mutation.DeletedAtCleared() {
		_spec.ClearField(mediaprocesstask.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := mptuo.mutation.MediaType(); ok {
		_spec.SetField(mediaprocesstask.FieldMediaType, field.TypeEnum, value)
	}
	if value, ok := mptuo.mutation.Status(); ok {
		_spec.SetField(mediaprocesstask.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := mptuo.mutation.EntityID(); ok {
		_spec.SetField(mediaprocesstask.FieldEntityID, field.TypeInt, value)
	}
	if value, ok := mptuo.mutation.AddedEntityID(); ok {
		_spec.AddField(mediaprocesstask.FieldEntityID, field.TypeInt, value)
	}
	if value, ok := mptuo.mutation.FileID(); ok {
		_spec.SetField(mediaprocesstask.FieldFileID, field.TypeInt, value)
	}
	if value, ok := mptuo.mutation.AddedFileID(); ok {
		_spec.AddField(mediaprocesstask.FieldFileID, field.TypeInt, value)
	}
	if mptuo.mutation.FileIDCleared() {
		_spec.ClearField(mediaprocesstask.FieldFileID, field.TypeInt)
	}
	if value, ok := mptuo.mutation.OwnerID(); ok {
		_spec.SetField(mediaprocesstask.FieldOwnerID, field.TypeInt, value)
	}
	if value, ok := mptuo.mutation.AddedOwnerID(); ok {
		_spec.AddField(mediaprocesstask.FieldOwnerID, field.TypeInt, value)
	}
	if value, ok := mptuo.mutation.Attempts(); ok {
		_spec.SetField(mediaprocesstask.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := mptuo.mutation.AddedAttempts(); ok {
		_spec.AddField(mediaprocesstask.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := mptuo.mutation.Error(); ok {
		_spec.SetField(mediaprocesstask.FieldError, field.TypeString, value)
	}
	if mptuo.mutation.ErrorCleared() {
		_spec.ClearField(mediaprocesstask.FieldError, field.TypeString)
	}
	if value, ok := mptuo.mutation.ResultSize(); ok {
		_spec.SetField(mediaprocesstask.FieldResultSize, field.TypeInt64, value)
	}
	if value, ok := mptuo.mutation.AddedResultSize(); ok {
		_spec.AddField(mediaprocesstask.FieldResultSize, field.TypeInt64, value)
	}
	if mptuo.mutation.ResultSizeCleared() {
		_spec.ClearField(mediaprocesstask.FieldResultSize, field.TypeInt64)
	}
	if value, ok := mptuo.mutation.Props(); ok {
		_spec.SetField(mediaprocesstask.FieldProps, field.TypeJSON, value)
	}
	if mptuo.mutation.PropsCleared() {
		_spec.ClearField(mediaprocesstask.FieldProps, field.TypeJSON)
	}
	_node = &MediaProcessTask{config: mptuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, mptuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mediaprocesstask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	mptuo.mutation.done = true
	return _node, nil
}
