// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/mediaprocesstask"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
)

// MediaProcessTaskDelete is the builder for deleting a MediaProcessTask entity.
type MediaProcessTaskDelete struct {
	config
	hooks    []Hook
	mutation *MediaProcessTaskMutation
}

// Where appends a list predicates to the MediaProcessTaskDelete builder.
func (mptd *MediaProcessTaskDelete) Where(ps ...predicate.MediaProcessTask) *MediaProcessTaskDelete {
	mptd.mutation.Where(ps...)
	return mptd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mptd *MediaProcessTaskDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, mptd.sqlExec, mptd.mutation, mptd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (mptd *MediaProcessTaskDelete) ExecX(ctx context.Context) int {
	n, err := mptd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mptd *MediaProcessTaskDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(mediaprocesstask.Table, sqlgraph.NewFieldSpec(mediaprocesstask.FieldID, field.TypeInt))
	if ps := mptd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, mptd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	mptd.mutation.done = true
	return affected, err
}

// MediaProcessTaskDeleteOne is the builder for deleting a single MediaProcessTask entity.
type MediaProcessTaskDeleteOne struct {
	mptd *MediaProcessTaskDelete
}

// Where appends a list predicates to the MediaProcessTaskDelete builder.
func (mptdo *MediaProcessTaskDeleteOne) Where(ps ...predicate.MediaProcessTask) *MediaProcessTaskDeleteOne {
	mptdo.mptd.mutation.Where(ps...)
	return mptdo
}

// Exec executes the deletion query.
func (mptdo *MediaProcessTaskDeleteOne) Exec(ctx context.Context) error {
	n, err := mptdo.mptd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{mediaprocesstask.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mptdo *MediaProcessTaskDeleteOne) ExecX(ctx context.Context) {
	if err := mptdo.Exec(ctx); err != nil {
		panic(err)
	}
}
