// Code generated by ent, DO NOT EDIT.

package mediaprocesstask

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldEQ(FieldDeletedAt, v))
}

// EntityID applies equality check predicate on the "entity_id" field. It's identical to EntityIDEQ.
func EntityID(v int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldEQ(FieldEntityID, v))
}

// FileID applies equality check predicate on the "file_id" field. It's identical to FileIDEQ.
func FileID(v int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldEQ(FieldFileID, v))
}

// OwnerID applies equality check predicate on the "owner_id" field. It's identical to OwnerIDEQ.
func OwnerID(v int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldEQ(FieldOwnerID, v))
}

// Attempts applies equality check predicate on the "attempts" field. It's identical to AttemptsEQ.
func Attempts(v int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldEQ(FieldAttempts, v))
}

// Error applies equality check predicate on the "error" field. It's identical to ErrorEQ.
func Error(v string) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldEQ(FieldError, v))
}

// ResultSize applies equality check predicate on the "result_size" field. It's identical to ResultSizeEQ.
func ResultSize(v int64) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldEQ(FieldResultSize, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldNotNull(FieldDeletedAt))
}

// MediaTypeEQ applies the EQ predicate on the "media_type" field.
func MediaTypeEQ(v MediaType) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldEQ(FieldMediaType, v))
}

// MediaTypeNEQ applies the NEQ predicate on the "media_type" field.
func MediaTypeNEQ(v MediaType) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldNEQ(FieldMediaType, v))
}

// MediaTypeIn applies the In predicate on the "media_type" field.
func MediaTypeIn(vs ...MediaType) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldIn(FieldMediaType, vs...))
}

// MediaTypeNotIn applies the NotIn predicate on the "media_type" field.
func MediaTypeNotIn(vs ...MediaType) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldNotIn(FieldMediaType, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldNotIn(FieldStatus, vs...))
}

// EntityIDEQ applies the EQ predicate on the "entity_id" field.
func EntityIDEQ(v int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldEQ(FieldEntityID, v))
}

// EntityIDNEQ applies the NEQ predicate on the "entity_id" field.
func EntityIDNEQ(v int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldNEQ(FieldEntityID, v))
}

// EntityIDIn applies the In predicate on the "entity_id" field.
func EntityIDIn(vs ...int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldIn(FieldEntityID, vs...))
}

// EntityIDNotIn applies the NotIn predicate on the "entity_id" field.
func EntityIDNotIn(vs ...int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldNotIn(FieldEntityID, vs...))
}

// EntityIDGT applies the GT predicate on the "entity_id" field.
func EntityIDGT(v int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldGT(FieldEntityID, v))
}

// EntityIDGTE applies the GTE predicate on the "entity_id" field.
func EntityIDGTE(v int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldGTE(FieldEntityID, v))
}

// EntityIDLT applies the LT predicate on the "entity_id" field.
func EntityIDLT(v int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldLT(FieldEntityID, v))
}

// EntityIDLTE applies the LTE predicate on the "entity_id" field.
func EntityIDLTE(v int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldLTE(FieldEntityID, v))
}

// FileIDEQ applies the EQ predicate on the "file_id" field.
func FileIDEQ(v int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldEQ(FieldFileID, v))
}

// FileIDNEQ applies the NEQ predicate on the "file_id" field.
func FileIDNEQ(v int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldNEQ(FieldFileID, v))
}

// FileIDIn applies the In predicate on the "file_id" field.
func FileIDIn(vs ...int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldIn(FieldFileID, vs...))
}

// FileIDNotIn applies the NotIn predicate on the "file_id" field.
func FileIDNotIn(vs ...int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldNotIn(FieldFileID, vs...))
}

// FileIDGT applies the GT predicate on the "file_id" field.
func FileIDGT(v int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldGT(FieldFileID, v))
}

// FileIDGTE applies the GTE predicate on the "file_id" field.
func FileIDGTE(v int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldGTE(FieldFileID, v))
}

// FileIDLT applies the LT predicate on the "file_id" field.
func FileIDLT(v int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldLT(FieldFileID, v))
}

// FileIDLTE applies the LTE predicate on the "file_id" field.
func FileIDLTE(v int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldLTE(FieldFileID, v))
}

// FileIDIsNil applies the IsNil predicate on the "file_id" field.
func FileIDIsNil() predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldIsNull(FieldFileID))
}

// FileIDNotNil applies the NotNil predicate on the "file_id" field.
func FileIDNotNil() predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldNotNull(FieldFileID))
}

// OwnerIDEQ applies the EQ predicate on the "owner_id" field.
func OwnerIDEQ(v int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldEQ(FieldOwnerID, v))
}

// OwnerIDNEQ applies the NEQ predicate on the "owner_id" field.
func OwnerIDNEQ(v int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldNEQ(FieldOwnerID, v))
}

// OwnerIDIn applies the In predicate on the "owner_id" field.
func OwnerIDIn(vs ...int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldIn(FieldOwnerID, vs...))
}

// OwnerIDNotIn applies the NotIn predicate on the "owner_id" field.
func OwnerIDNotIn(vs ...int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldNotIn(FieldOwnerID, vs...))
}

// OwnerIDGT applies the GT predicate on the "owner_id" field.
func OwnerIDGT(v int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldGT(FieldOwnerID, v))
}

// OwnerIDGTE applies the GTE predicate on the "owner_id" field.
func OwnerIDGTE(v int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldGTE(FieldOwnerID, v))
}

// OwnerIDLT applies the LT predicate on the "owner_id" field.
func OwnerIDLT(v int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldLT(FieldOwnerID, v))
}

// OwnerIDLTE applies the LTE predicate on the "owner_id" field.
func OwnerIDLTE(v int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldLTE(FieldOwnerID, v))
}

// AttemptsEQ applies the EQ predicate on the "attempts" field.
func AttemptsEQ(v int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldEQ(FieldAttempts, v))
}

// AttemptsNEQ applies the NEQ predicate on the "attempts" field.
func AttemptsNEQ(v int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldNEQ(FieldAttempts, v))
}

// AttemptsIn applies the In predicate on the "attempts" field.
func AttemptsIn(vs ...int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldIn(FieldAttempts, vs...))
}

// AttemptsNotIn applies the NotIn predicate on the "attempts" field.
func AttemptsNotIn(vs ...int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldNotIn(FieldAttempts, vs...))
}

// AttemptsGT applies the GT predicate on the "attempts" field.
func AttemptsGT(v int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldGT(FieldAttempts, v))
}

// AttemptsGTE applies the GTE predicate on the "attempts" field.
func AttemptsGTE(v int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldGTE(FieldAttempts, v))
}

// AttemptsLT applies the LT predicate on the "attempts" field.
func AttemptsLT(v int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldLT(FieldAttempts, v))
}

// AttemptsLTE applies the LTE predicate on the "attempts" field.
func AttemptsLTE(v int) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldLTE(FieldAttempts, v))
}

// ErrorEQ applies the EQ predicate on the "error" field.
func ErrorEQ(v string) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldEQ(FieldError, v))
}

// ErrorNEQ applies the NEQ predicate on the "error" field.
func ErrorNEQ(v string) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldNEQ(FieldError, v))
}

// ErrorIn applies the In predicate on the "error" field.
func ErrorIn(vs ...string) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldIn(FieldError, vs...))
}

// ErrorNotIn applies the NotIn predicate on the "error" field.
func ErrorNotIn(vs ...string) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldNotIn(FieldError, vs...))
}

// ErrorGT applies the GT predicate on the "error" field.
func ErrorGT(v string) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldGT(FieldError, v))
}

// ErrorGTE applies the GTE predicate on the "error" field.
func ErrorGTE(v string) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldGTE(FieldError, v))
}

// ErrorLT applies the LT predicate on the "error" field.
func ErrorLT(v string) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldLT(FieldError, v))
}

// ErrorLTE applies the LTE predicate on the "error" field.
func ErrorLTE(v string) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldLTE(FieldError, v))
}

// ErrorContains applies the Contains predicate on the "error" field.
func ErrorContains(v string) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldContains(FieldError, v))
}

// ErrorHasPrefix applies the HasPrefix predicate on the "error" field.
func ErrorHasPrefix(v string) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldHasPrefix(FieldError, v))
}

// ErrorHasSuffix applies the HasSuffix predicate on the "error" field.
func ErrorHasSuffix(v string) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldHasSuffix(FieldError, v))
}

// ErrorIsNil applies the IsNil predicate on the "error" field.
func ErrorIsNil() predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldIsNull(FieldError))
}

// ErrorNotNil applies the NotNil predicate on the "error" field.
func ErrorNotNil() predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldNotNull(FieldError))
}

// ErrorEqualFold applies the EqualFold predicate on the "error" field.
func ErrorEqualFold(v string) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldEqualFold(FieldError, v))
}

// ErrorContainsFold applies the ContainsFold predicate on the "error" field.
func ErrorContainsFold(v string) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldContainsFold(FieldError, v))
}

// ResultSizeEQ applies the EQ predicate on the "result_size" field.
func ResultSizeEQ(v int64) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldEQ(FieldResultSize, v))
}

// ResultSizeNEQ applies the NEQ predicate on the "result_size" field.
func ResultSizeNEQ(v int64) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldNEQ(FieldResultSize, v))
}

// ResultSizeIn applies the In predicate on the "result_size" field.
func ResultSizeIn(vs ...int64) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldIn(FieldResultSize, vs...))
}

// ResultSizeNotIn applies the NotIn predicate on the "result_size" field.
func ResultSizeNotIn(vs ...int64) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldNotIn(FieldResultSize, vs...))
}

// ResultSizeGT applies the GT predicate on the "result_size" field.
func ResultSizeGT(v int64) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldGT(FieldResultSize, v))
}

// ResultSizeGTE applies the GTE predicate on the "result_size" field.
func ResultSizeGTE(v int64) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldGTE(FieldResultSize, v))
}

// ResultSizeLT applies the LT predicate on the "result_size" field.
func ResultSizeLT(v int64) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldLT(FieldResultSize, v))
}

// ResultSizeLTE applies the LTE predicate on the "result_size" field.
func ResultSizeLTE(v int64) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldLTE(FieldResultSize, v))
}

// ResultSizeIsNil applies the IsNil predicate on the "result_size" field.
func ResultSizeIsNil() predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldIsNull(FieldResultSize))
}

// ResultSizeNotNil applies the NotNil predicate on the "result_size" field.
func ResultSizeNotNil() predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldNotNull(FieldResultSize))
}

// PropsIsNil applies the IsNil predicate on the "props" field.
func PropsIsNil() predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldIsNull(FieldProps))
}

// PropsNotNil applies the NotNil predicate on the "props" field.
func PropsNotNil() predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.FieldNotNull(FieldProps))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MediaProcessTask) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MediaProcessTask) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MediaProcessTask) predicate.MediaProcessTask {
	return predicate.MediaProcessTask(sql.NotPredicates(p))
}
